title: TKB — Teensy Keyboard Bridge
description: IBM Wheelwriter 6 interface via Teensy 4.0
remote_theme: just-the-docs/just-the-docs

color_scheme: light

aux_links:
  GitHub: https://github.com/Flopsstuff/neonka
